//
//  IngredientData.swift
//  GreenEats
//
//  Created by Felix Kramer on 29/7/17.
//  Copyright © 2017 Felix Kramer. All rights reserved.
//

import Foundation

class Data {
    class func getData() -> [IngredientClass] {
        var data = [IngredientClass]()
        
        data.append(IngredientClass(ingredientName: "Almonds", ingredientIcon: "almonds", emissionsPerKg: 1.8959732, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Almonds, organic", ingredientIcon: "almonds, organic", emissionsPerKg: 3.5714844, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Apples", ingredientIcon: "apples", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Apples, Fuji (premium)", ingredientIcon: "apples, fuji (premium)", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Apples, Fuji (standard)", ingredientIcon: "apples, fuji (standard)", emissionsPerKg: 0.1763696, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Apples, Granny Smith", ingredientIcon: "apples, granny smith", emissionsPerKg: 0.110231, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Apples, organic", ingredientIcon: "apples, organic", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Apricots", ingredientIcon: "apricots", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Arctic Char, farmed, filleted", ingredientIcon: "arctic char, farmed, filleted", emissionsPerKg: 18.4306232, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Artichokes", ingredientIcon: "artichokes", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Asparagus", ingredientIcon: "asparagus", emissionsPerKg: 0.881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Atlantic Cod", ingredientIcon: "atlantic cod", emissionsPerKg: 5.2690418, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Atlantic Salmon, farmed", ingredientIcon: "atlantic salmon, farmed", emissionsPerKg: 2.8880522, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Atlantic Salmon, farmed, filleted", ingredientIcon: "atlantic salmon, farmed, filleted", emissionsPerKg: 5.070626, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Bananas", ingredientIcon: "bananas", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Barley, Malting Barley", ingredientIcon: "barley, malting barley", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Barley, winter barley, organic", ingredientIcon: "barley, winter barley, organic", emissionsPerKg: 0.551155, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Baby Lima", ingredientIcon: "beans, baby lima", emissionsPerKg: 0.6393398, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Blackeye", ingredientIcon: "beans, blackeye", emissionsPerKg: 0.5732012, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Chinese Long Bean", ingredientIcon: "beans, chinese long bean", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, common dry varieties", ingredientIcon: "beans, common dry varieties", emissionsPerKg: 0.9479866, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Dry Beans", ingredientIcon: "beans, dry beans", emissionsPerKg: 0.7936632, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Dry Beans, organic", ingredientIcon: "beans, dry beans, organic", emissionsPerKg: 0.5291088, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Green, Blue Lake Variety", ingredientIcon: "beans, green, blue lake variety", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Large Lima", ingredientIcon: "beans, large lima", emissionsPerKg: 1.1464024, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Lima/Blackeye", ingredientIcon: "beans, lima/blackeye", emissionsPerKg: 0.7495708, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beans, Snap Beans", ingredientIcon: "beans, snap beans", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beef Meat, pasture-fed", ingredientIcon: "beef meat, pasture-fed", emissionsPerKg: 16.4905576, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beef Meat, ration-fed", ingredientIcon: "beef meat, ration-fed", emissionsPerKg: 17.63696, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beer", ingredientIcon: "beer", emissionsPerKg: 0.3747854, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Beets, Sugarbeets", ingredientIcon: "beets, sugarbeets", emissionsPerKg: 0.0440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Bittermelon", ingredientIcon: "bittermelon", emissionsPerKg: 0.110231, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Black Raspberry", ingredientIcon: "black raspberry", emissionsPerKg: 0.5732012, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Blackberries", ingredientIcon: "blackberries", emissionsPerKg: 0.2866006, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Blueberries, Highbush", ingredientIcon: "blueberries, highbush", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Blueberries, Highbush, organic", ingredientIcon: "blueberries, highbush, organic", emissionsPerKg: 0.7275246, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Boysenberries", ingredientIcon: "boysenberries", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Bread Flour", ingredientIcon: "bread flour", emissionsPerKg: 0.551155, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Broccoli", ingredientIcon: "broccoli", emissionsPerKg: 0.3527392, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Broccoli, organic", ingredientIcon: "broccoli, organic", emissionsPerKg: 0.4188778, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Brussels Sprouts", ingredientIcon: "brussels sprouts", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Butter", ingredientIcon: "butter", emissionsPerKg: 1.1684486, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cabbage", ingredientIcon: "cabbage", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cabbage, chinese", ingredientIcon: "cabbage, chinese", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Canola, Spring Canola", ingredientIcon: "canola, spring canola", emissionsPerKg: 0.8598018, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cantaloupe", ingredientIcon: "cantaloupe", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Carrots", ingredientIcon: "carrots", emissionsPerKg: 0.110231, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Catfish, farmed, farmed", ingredientIcon: "catfish, farmed, farmed", emissionsPerKg: 4.7178868, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Catfish, farmed, farmed, filleted", ingredientIcon: "catfish, farmed, farmed, filleted", emissionsPerKg: 9.369635, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cauliflower", ingredientIcon: "cauliflower", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Celery", ingredientIcon: "celery", emissionsPerKg: 0.110231, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cheese, cottage", ingredientIcon: "cheese, cottage", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cheese, natural", ingredientIcon: "cheese, natural", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cheese, processed", ingredientIcon: "cheese, processed", emissionsPerKg: 9.8546514, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cherries", ingredientIcon: "cherries", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cherries, Sweet Cherries", ingredientIcon: "cherries, sweet cherries", emissionsPerKg: 0.7936632, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Chicken Meat (broiler), large-scale, confinement", ingredientIcon: "chicken meat (broiler), large-scale, confinement", emissionsPerKg: 3.747854, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Chicken Meat (broiler), small-scale, free-range", ingredientIcon: "chicken meat (broiler), small-scale, free-range", emissionsPerKg: 5.5997348, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cilantro", ingredientIcon: "cilantro", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cocoa Beans", ingredientIcon: "cocoa beans", emissionsPerKg: 0.5732012, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cocoa Butter", ingredientIcon: "cocoa butter", emissionsPerKg: 1.1464024, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cocoa Cake", ingredientIcon: "cocoa cake", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cocoa Liquor (unsweetened chocolate liquid)", ingredientIcon: "cocoa liquor (unsweetened chocolate liquid)", emissionsPerKg: 0.8157094, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cocoa Powder", ingredientIcon: "cocoa powder", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Coffee", ingredientIcon: "coffee", emissionsPerKg: 2.5132668, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Coffee Beans, green", ingredientIcon: "coffee beans, green", emissionsPerKg: 1.653465, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Common Carp, farmed", ingredientIcon: "common carp, farmed", emissionsPerKg: 5.3131342, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Common Carp, farmed, filleted", ingredientIcon: "common carp, farmed, filleted", emissionsPerKg: 9.5680508, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cooking/Salad Oil", ingredientIcon: "cooking/salad oil", emissionsPerKg: 1.7416498, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn", ingredientIcon: "corn", emissionsPerKg: 0.5952474, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn", ingredientIcon: "corn", emissionsPerKg: 0.5952474, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn Feed", ingredientIcon: "corn feed", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn Oil", ingredientIcon: "corn oil", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn Syrup", ingredientIcon: "corn syrup", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn, organic", ingredientIcon: "corn, organic", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Corn, Sweet Corn", ingredientIcon: "corn, sweet corn", emissionsPerKg: 0.3527392, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cream, sour", ingredientIcon: "cream, sour", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cream, whipped fluid", ingredientIcon: "cream, whipped fluid", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cucumbers", ingredientIcon: "cucumbers", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cucurbits, Moqua/Opo", ingredientIcon: "cucurbits, moqua/opo", emissionsPerKg: 0.0661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Cucurbits, Sinqua", ingredientIcon: "cucurbits, sinqua", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Daikon Radish", ingredientIcon: "daikon radish", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Dates, Deglet Noor (Grade B, US Choice)", ingredientIcon: "dates, deglet noor (grade b, us choice)", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Dates, Deglet Noor (Grade C, US Standard)", ingredientIcon: "dates, deglet noor (grade c, us standard)", emissionsPerKg: 0.1763696, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Eggplants, American Style", ingredientIcon: "eggplants, american style", emissionsPerKg: 0.5070626, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Eggplants, Asian Style", ingredientIcon: "eggplants, asian style", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Eggs (Grade A, X Large, Jumbo, and Medium), large-scale, free-range", ingredientIcon: "eggs (grade a, x large, jumbo, and medium), large-scale, free-range", emissionsPerKg: 2.0282504, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Eggs (Grade A, X Large, Jumbo, and Medium), large-scale, free-range, commercial ration", ingredientIcon: "eggs (grade a, x large, jumbo, and medium), large-scale, free-range, commercial ration", emissionsPerKg: 2.3809896, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Eggs (Jumbo, X-Large, Large, Medium, Small), large-scale, confinement, commercial ration", ingredientIcon: "eggs (jumbo, x-large, large, medium, small), large-scale, confinement, commercial ration", emissionsPerKg: 1.8518808, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Eggs (X-Large, Jumbo, Large, and Medium), small-scale, free-range", ingredientIcon: "eggs (x-large, jumbo, large, and medium), small-scale, free-range", emissionsPerKg: 1.8959732, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Figs", ingredientIcon: "figs", emissionsPerKg: 1.543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Figs, Black Mission", ingredientIcon: "figs, black mission", emissionsPerKg: 0.6834322, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Flatfish", ingredientIcon: "flatfish", emissionsPerKg: 5.9965664, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Flatfish, filleted", ingredientIcon: "flatfish, filleted", emissionsPerKg: 3.0644218, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Flour", ingredientIcon: "flour", emissionsPerKg: 0.6393398, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Frozen Orange Juice", ingredientIcon: "frozen orange juice", emissionsPerKg: 7.9807244, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Garbanzos (chick-peas)", ingredientIcon: "garbanzos (chick-peas)", emissionsPerKg: 0.6393398, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Garlic", ingredientIcon: "garlic", emissionsPerKg: 0.9479866, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes", ingredientIcon: "grapes", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Cabernet Sauvignon, for wine", ingredientIcon: "grapes, cabernet sauvignon, for wine", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Chardonnay, for wine", ingredientIcon: "grapes, chardonnay, for wine", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Chardonnay, for wine, organic", ingredientIcon: "grapes, chardonnay, for wine, organic", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Crimson Seedless", ingredientIcon: "grapes, crimson seedless", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Flame Seedless", ingredientIcon: "grapes, flame seedless", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, for raisins", ingredientIcon: "grapes, for raisins", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, French Hybrids, for wine", ingredientIcon: "grapes, french hybrids, for wine", emissionsPerKg: 0.4850164, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Redglobe", ingredientIcon: "grapes, redglobe", emissionsPerKg: 0.1763696, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Sauvignon Blanc, for wine", ingredientIcon: "grapes, sauvignon blanc, for wine", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Spur Pruned Varieties", ingredientIcon: "grapes, spur pruned varieties", emissionsPerKg: 0.0661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Thompson Seedless", ingredientIcon: "grapes, thompson seedless", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Grapes, Thompson Seedless/Fiesta, organic", ingredientIcon: "grapes, thompson seedless/fiesta, organic", emissionsPerKg: 0.7054784, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Guava, Tropical Pink", ingredientIcon: "guava, tropical pink", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Hams", ingredientIcon: "hams", emissionsPerKg: 9.3255426, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Hash Brown/Fried Potatoes", ingredientIcon: "hash brown/fried potatoes", emissionsPerKg: 3.968316, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Herring", ingredientIcon: "herring", emissionsPerKg: 2.094389, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Herring, filleted", ingredientIcon: "herring, filleted", emissionsPerKg: 1.2345872, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Ice Cream", ingredientIcon: "ice cream", emissionsPerKg: 1.8298346, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Industrial Fish", ingredientIcon: "industrial fish", emissionsPerKg: 1.1243562, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lamb Meat, ration-fed", ingredientIcon: "lamb meat, ration-fed", emissionsPerKg: 24.9342522, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lemongrass", ingredientIcon: "lemongrass", emissionsPerKg: 0.0661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lemons, Lisbon Variety", ingredientIcon: "lemons, lisbon variety", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lentils", ingredientIcon: "lentils", emissionsPerKg: 0.5291088, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lettuce, crisp-head", ingredientIcon: "lettuce, crisp-head", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lettuce, greenhouse", ingredientIcon: "lettuce, greenhouse", emissionsPerKg: 9.8326052, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lettuce, Iceberg", ingredientIcon: "lettuce, iceberg", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lettuce, Leaf, organic", ingredientIcon: "lettuce, leaf, organic", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lettuce, loose-leaf ", ingredientIcon: "lettuce, loose-leaf ", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Lettuce, Romaine Hearts", ingredientIcon: "lettuce, romaine hearts", emissionsPerKg: 0.9259404, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Liquid Eggs", ingredientIcon: "liquid eggs", emissionsPerKg: 2.1605276, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Macaroni/Spaghetti/Pasta", ingredientIcon: "macaroni/spaghetti/pasta", emissionsPerKg: 1.2345872, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mackerel", ingredientIcon: "mackerel", emissionsPerKg: 1.1464024, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mackerel, filleted", ingredientIcon: "mackerel, filleted", emissionsPerKg: 1.9180194, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Malaysian Shrimp/Prawn, farmed", ingredientIcon: "malaysian shrimp/prawn, farmed", emissionsPerKg: 4.2769628, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Malt Whisky", ingredientIcon: "malt whisky", emissionsPerKg: 2.7337288, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Malted Barley", ingredientIcon: "malted barley", emissionsPerKg: 0.8598018, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mandarin Oranges, Satsuma", ingredientIcon: "mandarin oranges, satsuma", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mango, organic", ingredientIcon: "mango, organic", emissionsPerKg: 0.0661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Margarine", ingredientIcon: "margarine", emissionsPerKg: 1.763696, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Marinara Sauce", ingredientIcon: "marinara sauce", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mashed Potato Flakes", ingredientIcon: "mashed potato flakes", emissionsPerKg: 4.519471, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mashed Potato Granules", ingredientIcon: "mashed potato granules", emissionsPerKg: 4.3210552, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Medium White Wine", ingredientIcon: "medium white wine", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Melons, cantaloupe/watermelon/honeydew/specialty", ingredientIcon: "melons, cantaloupe/watermelon/honeydew/specialty", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Milk, evaporated", ingredientIcon: "milk, evaporated", emissionsPerKg: 2.5132668, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Milk, powdered", ingredientIcon: "milk, powdered", emissionsPerKg: 9.7444204, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Milk, processed, 2% MF", ingredientIcon: "milk, processed, 2% mf", emissionsPerKg: 0.7936632, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Milk, whole, raw", ingredientIcon: "milk, whole, raw", emissionsPerKg: 1.0141252, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Milk, whole, raw", ingredientIcon: "milk, whole, raw", emissionsPerKg: 1.0141252, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mullet, , farmed", ingredientIcon: "mullet, , farmed", emissionsPerKg: 5.3131342, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mushrooms, Portabella/Button", ingredientIcon: "mushrooms, portabella/button", emissionsPerKg: 0, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Mussels, farmed", ingredientIcon: "mussels, farmed", emissionsPerKg: 0.5291088, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Nectarines", ingredientIcon: "nectarines", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "New Red Wine", ingredientIcon: "new red wine", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Norway Lobster", ingredientIcon: "norway lobster", emissionsPerKg: 5.3792728, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oat Bran", ingredientIcon: "oat bran", emissionsPerKg: 0.4850164, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oatmeal (rolled oat flakes)", ingredientIcon: "oatmeal (rolled oat flakes)", emissionsPerKg: 0.4850164, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oats", ingredientIcon: "oats", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Okra", ingredientIcon: "okra", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Olives, Arbequena", ingredientIcon: "olives, arbequena", emissionsPerKg: 0.2866006, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Olives, Manzanillo", ingredientIcon: "olives, manzanillo", emissionsPerKg: 0.1984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Onions", ingredientIcon: "onions", emissionsPerKg: 0.2866006, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Onions", ingredientIcon: "onions", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Onions, Red (Early Red Burger Variety)", ingredientIcon: "onions, red (early red burger variety)", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Orange Juice", ingredientIcon: "orange juice", emissionsPerKg: 2.1384814, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oranges, Blood Oranges", ingredientIcon: "oranges, blood oranges", emissionsPerKg: 0.1763696, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oranges, Minneola (Tangelo)", ingredientIcon: "oranges, minneola (tangelo)", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oranges, Navel/Valencias", ingredientIcon: "oranges, navel/valencias", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oranges, Valencia", ingredientIcon: "oranges, valencia", emissionsPerKg: 1.4550492, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Oyster, farmed", ingredientIcon: "oyster, farmed", emissionsPerKg: 11.4419778, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Palm Fruit", ingredientIcon: "palm fruit", emissionsPerKg: 0.0661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Palm Kernel Oil", ingredientIcon: "palm kernel oil", emissionsPerKg: 0.9038942, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Palm Kernels", ingredientIcon: "palm kernels", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Palm Oil", ingredientIcon: "palm oil", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Parsley", ingredientIcon: "parsley", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Partially Hydrogenated Vegetable Oil", ingredientIcon: "partially hydrogenated vegetable oil", emissionsPerKg: 1.7857422, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pastry Flour", ingredientIcon: "pastry flour", emissionsPerKg: 0.5291088, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peaches", ingredientIcon: "peaches", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peanut Butter", ingredientIcon: "peanut butter", emissionsPerKg: 1.5211878, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peanut Oil", ingredientIcon: "peanut oil", emissionsPerKg: 3.9021774, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peanuts", ingredientIcon: "peanuts", emissionsPerKg: 0.5732012, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pears, Green Bartlett", ingredientIcon: "pears, green bartlett", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pears, Specialty Pears", ingredientIcon: "pears, specialty pears", emissionsPerKg: 0.1322772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peas, Spring Peas", ingredientIcon: "peas, spring peas", emissionsPerKg: 0.2866006, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pecans", ingredientIcon: "pecans", emissionsPerKg: 1.6093726, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peppermint, Black Mitchum Variety", ingredientIcon: "peppermint, black mitchum variety", emissionsPerKg: 45.0183404, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pepperoni", ingredientIcon: "pepperoni", emissionsPerKg: 13.0733966, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Peppers, Bell", ingredientIcon: "peppers, bell", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pineapple", ingredientIcon: "pineapple", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pineapple, organic", ingredientIcon: "pineapple, organic", emissionsPerKg: 0.0881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pistachios", ingredientIcon: "pistachios", emissionsPerKg: 1.1243562, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pita Bread", ingredientIcon: "pita bread", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pizza Dough", ingredientIcon: "pizza dough", emissionsPerKg: 0.7275246, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Plums", ingredientIcon: "plums", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pomegranates", ingredientIcon: "pomegranates", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pork Meat, full confinement", ingredientIcon: "pork meat, full confinement", emissionsPerKg: 5.4674576, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pork Meat, pasture access", ingredientIcon: "pork meat, pasture access", emissionsPerKg: 6.1067974, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Potato Chips", ingredientIcon: "potato chips", emissionsPerKg: 3.4392072, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Potatoes", ingredientIcon: "potatoes", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Potatoes, Russet Burbank", ingredientIcon: "potatoes, russet burbank", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Premium Red Wine", ingredientIcon: "premium red wine", emissionsPerKg: 0.4188778, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Premium White Wine", ingredientIcon: "premium white wine", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Prunes (dried plums), French Variety", ingredientIcon: "prunes (dried plums), french variety", emissionsPerKg: 0.5070626, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pummelos (specialty citrus fruit)", ingredientIcon: "pummelos (specialty citrus fruit)", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Pumpkins", ingredientIcon: "pumpkins", emissionsPerKg: 0.1543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rape Seed, summer rape", ingredientIcon: "rape seed, summer rape", emissionsPerKg: 0.881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rape Seed, winter rape", ingredientIcon: "rape seed, winter rape", emissionsPerKg: 0.5732012, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rapeseed/Canola Oil", ingredientIcon: "rapeseed/canola oil", emissionsPerKg: 1.6975574, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Raspberries", ingredientIcon: "raspberries", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, bran", ingredientIcon: "rice, bran", emissionsPerKg: 0.4629702, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, bran", ingredientIcon: "rice, bran", emissionsPerKg: 0.4629702, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, brown", ingredientIcon: "rice, brown", emissionsPerKg: 2.1605276, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, raw", ingredientIcon: "rice, raw", emissionsPerKg: 1.5211878, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, white", ingredientIcon: "rice, white", emissionsPerKg: 2.3589434, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, wild , brown", ingredientIcon: "rice, wild , brown", emissionsPerKg: 11.1553772, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, wild, bran", ingredientIcon: "rice, wild, bran", emissionsPerKg: 2.3809896, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, wild, raw", ingredientIcon: "rice, wild, raw", emissionsPerKg: 8.7302952, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rice, wild, white", ingredientIcon: "rice, wild, white", emissionsPerKg: 12.1474562, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rye", ingredientIcon: "rye", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Rye, organic", ingredientIcon: "rye, organic", emissionsPerKg: 0.440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Salt", ingredientIcon: "salt", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sausages", ingredientIcon: "sausages", emissionsPerKg: 9.369635, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sea Bass, farmed", ingredientIcon: "sea bass, farmed", emissionsPerKg: 5.2469956, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sea Bass, farmed, filleted", ingredientIcon: "sea bass, farmed, filleted", emissionsPerKg: 10.4278526, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Shrimp, farmed", ingredientIcon: "shrimp, farmed", emissionsPerKg: 7.054784, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Shrimp/Prawn", ingredientIcon: "shrimp/prawn", emissionsPerKg: 4.5856096, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Silver Carp", ingredientIcon: "silver carp", emissionsPerKg: 5.3131342, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Silver Carp, farmed, filleted", ingredientIcon: "silver carp, farmed, filleted", emissionsPerKg: 9.5680508, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soft Drinks", ingredientIcon: "soft drinks", emissionsPerKg: 1.7196036, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Solid Shortening", ingredientIcon: "solid shortening", emissionsPerKg: 1.8077884, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sorghum", ingredientIcon: "sorghum", emissionsPerKg: 0.2866006, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soybean Meal", ingredientIcon: "soybean meal", emissionsPerKg: 0.661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soybean Oil", ingredientIcon: "soybean oil", emissionsPerKg: 1.4770954, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soybeans", ingredientIcon: "soybeans", emissionsPerKg: 0.551155, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soybeans, Clark Variety", ingredientIcon: "soybeans, clark variety", emissionsPerKg: 0.4188778, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soybeans, organic", ingredientIcon: "soybeans, organic", emissionsPerKg: 0.5732012, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soymilk", ingredientIcon: "soymilk", emissionsPerKg: 0.6834322, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Soymilk, organic", ingredientIcon: "soymilk, organic", emissionsPerKg: 0.6834322, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Spinach", ingredientIcon: "spinach", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sponge Cake", ingredientIcon: "sponge cake", emissionsPerKg: 1.0361714, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Squash, Summer Squash", ingredientIcon: "squash, summer squash", emissionsPerKg: 0.3527392, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Squash, winter Squash", ingredientIcon: "squash, winter squash", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Strawberries", ingredientIcon: "strawberries", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Strawberries, organic", ingredientIcon: "strawberries, organic", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sugar Cookies", ingredientIcon: "sugar cookies", emissionsPerKg: 1.3007258, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sugar, raw cane", ingredientIcon: "sugar, raw cane", emissionsPerKg: 3.0203294, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sugar, refined cane", ingredientIcon: "sugar, refined cane", emissionsPerKg: 3.9462698, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sugarcane", ingredientIcon: "sugarcane", emissionsPerKg: 0.0440924, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sunflower Oil", ingredientIcon: "sunflower oil", emissionsPerKg: 1.4770954, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sunflower Seed", ingredientIcon: "sunflower seed", emissionsPerKg: 0.881848, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Sweet Potatoes", ingredientIcon: "sweet potatoes", emissionsPerKg: 0.4188778, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tilapia, farmed", ingredientIcon: "tilapia, farmed", emissionsPerKg: 5.3131342, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tilapia, farmed, filleted", ingredientIcon: "tilapia, farmed, filleted", emissionsPerKg: 10.5601298, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Toasted Breakfast Cereal", ingredientIcon: "toasted breakfast cereal", emissionsPerKg: 2.1605276, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Toasted Whole Wheat Breakfast Cereal", ingredientIcon: "toasted whole wheat breakfast cereal", emissionsPerKg: 2.0723428, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tofu, firm", ingredientIcon: "tofu, firm", emissionsPerKg: 0.7054784, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tofu, firm, organic", ingredientIcon: "tofu, firm, organic", emissionsPerKg: 0.6834322, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tomato Ketchup", ingredientIcon: "tomato ketchup", emissionsPerKg: 2.2487124, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tomato Paste", ingredientIcon: "tomato paste", emissionsPerKg: 1.8298346, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tomatoes", ingredientIcon: "tomatoes", emissionsPerKg: 0.2425082, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tomatoes, Cherry", ingredientIcon: "tomatoes, cherry", emissionsPerKg: 0.0661386, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tomatoes, organic", ingredientIcon: "tomatoes, organic", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Trout, farmed", ingredientIcon: "trout, farmed", emissionsPerKg: 2.5132668, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Trout, freshwater, farmed, filleted", ingredientIcon: "trout, freshwater, farmed, filleted", emissionsPerKg: 4.4312862, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tuna (Skipjack and Yellofin)", ingredientIcon: "tuna (skipjack and yellofin)", emissionsPerKg: 1.984158, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tuna, cooked, for canning", ingredientIcon: "tuna, cooked, for canning", emissionsPerKg: 4.078547, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Tuna, filleted", ingredientIcon: "tuna, filleted", emissionsPerKg: 3.4392072, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Turkey Meat (Hens), small-scale, confinement", ingredientIcon: "turkey meat (hens), small-scale, confinement", emissionsPerKg: 4.6737944, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Turkey Meat (Toms), small-scale, confinement", ingredientIcon: "turkey meat (toms), small-scale, confinement", emissionsPerKg: 4.519471, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Untoasted Breakfast Cereal", ingredientIcon: "untoasted breakfast cereal", emissionsPerKg: 1.543234, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Untoasted Whole Wheat Breakfast Cereal", ingredientIcon: "untoasted whole wheat breakfast cereal", emissionsPerKg: 1.4550492, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Walnuts,  conventional (micro-sprinkler irrig.)", ingredientIcon: "walnuts,  conventional (micro-sprinkler irrig.)", emissionsPerKg: 0.771617, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Walnuts, Chandler Variety", ingredientIcon: "walnuts, chandler variety", emissionsPerKg: 0.4850164, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Walnuts, English Variety", ingredientIcon: "walnuts, english variety", emissionsPerKg: 0.9038942, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat Bran", ingredientIcon: "wheat bran", emissionsPerKg: 0.551155, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat Bread", ingredientIcon: "wheat bread", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat Bread Rolls", ingredientIcon: "wheat bread rolls", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat Germ", ingredientIcon: "wheat germ", emissionsPerKg: 0.551155, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat, Hard Red Spring Wheat", ingredientIcon: "wheat, hard red spring wheat", emissionsPerKg: 0.3527392, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat, Hard White Spring Wheat", ingredientIcon: "wheat, hard white spring wheat", emissionsPerKg: 0.330693, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat, Soft White Spring Wheat", ingredientIcon: "wheat, soft white spring wheat", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat, Soft White Winter Wheat", ingredientIcon: "wheat, soft white winter wheat", emissionsPerKg: 0.3086468, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat, Spring Wheat", ingredientIcon: "wheat, spring wheat", emissionsPerKg: 0.2645544, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wheat, winter Wheat", ingredientIcon: "wheat, winter wheat", emissionsPerKg: 0.220462, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Whey, dry, natural", ingredientIcon: "whey, dry, natural", emissionsPerKg: 2.0282504, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Whole Wheat Bread", ingredientIcon: "whole wheat bread", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Whole Wheat Bread Rolls", ingredientIcon: "whole wheat bread rolls", emissionsPerKg: 0.8377556, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Whole Wheat Flour", ingredientIcon: "whole wheat flour", emissionsPerKg: 0.551155, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Whole Wheat Macaroni/Spaghetti/Pasta", ingredientIcon: "whole wheat macaroni/spaghetti/pasta", emissionsPerKg: 1.0582176, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Wine", ingredientIcon: "wine", emissionsPerKg: 0.6393398, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Yellow Mustard", ingredientIcon: "yellow mustard", emissionsPerKg: 0.992079, standardPortionName: "each", standardPortionSizeKg: 0.1))
        data.append(IngredientClass(ingredientName: "Yogurt", ingredientIcon: "yogurt", emissionsPerKg: 0.9038942, standardPortionName: "each", standardPortionSizeKg: 0.1))
        
        return data
    }
}
